# Generated by Django 5.0.2 on 2024-02-22 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('best_for_season', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.DateField(auto_now_add=True)),
                ('tours', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tours.tours')),
            ],
        ),
    ]
